# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Infrastructure\Controller\Activity\AddActivityController:
        arguments:
            - {
                adventure_activity : '@App\Application\Activity\AdventureActivity\Add\AddAdventureActivityService',
                online_game_activity : '@App\Application\Activity\OnlineGameActivity\Add\AddOnlineGameActivityService',
                sports_activity : '@App\Application\Activity\SportsActivity\Add\AddSportsActivityService'
            }

    App\Application\Activity\AdventureActivity\Add\AddAdventureActivityService:
        arguments:
            - '@App\Infrastructure\Repository\Activity\AdventureActivity\AdventureActivityRepositoryMySQL'

    App\Application\Activity\OnlineGameActivity\Add\AddOnlineGameActivityService:
        arguments:
            - '@App\Infrastructure\Repository\Activity\OnlineGameActivity\OnlineGameActivityRepositoryMySQL'

    App\Application\Activity\SportsActivity\Add\AddSportsActivityService:
        arguments:
            - '@App\Infrastructure\Repository\Activity\SportsActivity\SportsActivityRepositoryMySQL'

    App\Application\Activity\Find\FindActivitiesService:
        arguments:
            - {
                adventure_activity : '@App\Infrastructure\Repository\Activity\AdventureActivity\AdventureActivityRepositoryMySQL',
                online_game_activity : '@App\Infrastructure\Repository\Activity\OnlineGameActivity\OnlineGameActivityRepositoryMySQL',
                sports_activity : '@App\Infrastructure\Repository\Activity\SportsActivity\SportsActivityRepositoryMySQL'
            }
            - '@App\Application\Activity\Adapter\ActivityCollectionAdapter'
            - '@App\Application\Activity\ActivityRepository\ActivityRepositoryCriteriaBuilder'

    App\Application\Activity\Adapter\ActivityCollectionAdapter:
        arguments:
            - {
                adventure_activity : '@App\Application\Activity\AdventureActivity\Adapter\AdventureActivityAdapter',
                online_game_activity : '@App\Application\Activity\OnlineGameActivity\Adapter\OnlineGameActivityAdapter',
                sports_activity : '@App\Application\Activity\SportsActivity\Adapter\SportsActivityAdapter'
            }
